### PR TITLE
Add tests and enable travis ci

### PR DESCRIPTION
**Pull request by robbyoconnor**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
[Build Status](https://travis-ci.org/robbyoconnor/ansible-timezone)

**Comment by yatesr** [comment]
Thanks, Does this also check to make sure the timezone was changed.  For example checking the output of `date` before running the role and then checking it after the run to see if the timezone is the desired one specified.

**Comment by robbyoconnor** [comment]
No, but I can do that -- leave it open -- don't merge yet

**Comment by bbaassssiiee** [comment]
Superseded by https://github.com/yatesr/ansible-timezone/pull/9

**Pull request closed without merging**
